### ISSUE TITLE
Occasionally, my in-window AC's LED panel is being 'turned on' when it was 'turned off' in the native iOS app.

### ISSUE THREAD

**Issue by homekitter** [andersonshatch/midea-ac-py#12]
**Describe the bug**
Occasionally, my in-window AC's LED panel is being 'turned on' when it was 'turned off' in the native iOS app.

**To Reproduce**
Am unable to reproduce the issue as it is unpredictable.

**Expected behavior**
I expect that the AC's LED panel stays off when off, and stays on when on as per the iOS app.

**Screenshots / Logs**
Not yet.

**Versions**
 - Home Assistant version: Home Assistant 0.97.2 (Hassio)
 - Midea integration version (commit hash): Not yet. Just updated to f5df6ce

**Additional context**
Have just Add any other context about the problem here.

**Comment by homekitter** [comment]
Many thanks for your fine work!

**Comment by andersonshatch** [comment]
When you say occasionally, I assume not as regularly as once a minute like with the fan only issue?
If you don't need state updates (i.e. only control your AC from home-assistant), it would be interesting to see if this happens with the fan only workaround turned on.

That said, this is probably an issue in the underlying midea cloud library not sending the right commands, which is responsible for the fan only bug too; but not sure how to address issues there, as there are no docs for what each bit means. I suppose we could do lots of trial and error :)

My device has a display which shows the current temperature, but the toggle for this (annoyingly) isn't exposed in the app, only by IR remote toggle.

**Comment by homekitter** [comment]
My AC is a Toshiba RAC-WK0811ESCWC (AKA in the US as the RAC-WK0811ESCWU)

https://www.homedepot.ca/product/toshiba-8-000-btu-115v-smart-window-air-conditioner-with-remote-energy-star-/1001214540

https://us.toshiba-lifestyle.com/products/us/Room-Air-Conditioners/Window-A-C/8,000-BTU-Wi-Fi-Enabled-Window-Air-Conditioner-with-Remote-Controller.html

Attached you'll find a simulation (not reproduction) of the problem.

Normal operation, you can 'turn off' or 'turn on' the LED panel.

The LED panel occasionally coming on in the middle of the night is causing me to wake up.

![NOT_REPRODUCTION_But_Simulation_Of_Issue](https://user-images.githubusercontent.com/51726098/62975505-813f9180-bde8-11e9-9e2c-3387f6bf24f4.gif)

**Comment by homekitter** [comment]
I would have to say definitely not once a minute. Like 2-8 times a night. Unsure, as I am quite convinced I'm not waking on every occurrence but do vaguely recall shutting the LED panel off at least 4-5 times a night.

**Comment by homekitter** [comment]
I'd be happy to provide logs if I can. Would you point me to a path I should retrieve?

**Comment by andersonshatch** [comment]
Can you turn on [debug logging first](https://github.com/andersonshatch/midea-ac-py/wiki/Debug-logging-configuration) -- then entries will be emitted to your regular homeassistant.log file for each request.
If you can note down some of the times that happens it would be useful for correlating against the log.

Curious too if you've any idea if it's only changing the LED status or some other things too (temperature, fan speed, mode etc.,)?

**Comment by homekitter** [comment]
[midea-redacted.log](https://github.com/andersonshatch/midea-ac-py/files/3499261/midea-redacted.log)

Logging seems to be working…

**Comment by homekitter** [comment]
[midea-redacted.log](https://github.com/andersonshatch/midea-ac-py/files/3499658/midea-redacted.log)
Just happened. Was able to grab log.

**Comment by homekitter** [comment]
[midea-redacted.log](https://github.com/andersonshatch/midea-ac-py/files/3499672/midea-redacted.log)
Happened about 10 mins ago.

**Comment by andersonshatch** [comment]
Hmm, so a bunch of state updates and failures for them. 
Try with the fan only workaround which disables state updates, that could make a difference.

**Comment by homekitter** [comment]
Took me a little bit to find the article, but added use_fan_only_workaround: true as prescribed.

**Comment by andersonshatch** [comment]
Did that work?

**Comment by homekitter** [comment]
> Did that work?

I must report that 'use_fan_only_workaround: true' did nothing to help the matter.

I am happy to report that the problem was wholly unrelated to your fine work!

Issue recap: LED panel spontaneously 'turning on' when previously 'off'.

Root cause: Poor troubleshooting on my part and overlooking an unrelated automation that was cutting and restoring power to the Toshiba Window AC (RAC-WK0811ESCWC AKA in the US as the RAC-WK0811ESCWU)

Problem synopsis: Before your fine work was available, I was using a temperature sensor in the same room to trigger an iDevices switch. I neglected to confirm that that automation had been disabled. Once that (now unnecessary) automation was disabled, the LED panel stayed in the state set.

Please close this issue!
