### ISSUE TITLE
AC keeps changes to fan only

### ISSUE THREAD

**Issue by georgesofianosgr** [andersonshatch/midea-ac-py#17]
**Describe the bug**
Integration keeps changing AC to fan only. Even if i change it from mobile or remote.

**To Reproduce**
1. Install integration from hacs

**Expected behavior**
Keep state

**Versions**
 - Home Assistant version: 0.103.4
 - Midea integration version (commit hash): f5df6ce4fc3e3a718525893f770ac41a441adfb5

**Notes**
use_fan_only_workaround is set to true

**Comment by Maczuga** [comment]
It's already mentioned in README file.

https://github.com/andersonshatch/midea-ac-py#fan-only-workaround

**Comment by georgesofianosgr** [comment]
The README states:

> If you find this component turns your device on and to fan_only every time home-assistant updates it (once a minute by default), you probably want to turn on the workaround with this config property:
use_fan_only_workaround: true

I have already set use_fan_only_workaround to true but is not working.

**Comment by Maczuga** [comment]
What's your exact AC model? Seems like some new offsets might be needed.

**Comment by georgesofianosgr** [comment]
Ok I re-installed the integration and restarted HA after turning off/on the AC. 
I don't know what changed but it doesn't forces fan only now.
