### ISSUE TITLE
0.94 -> 0.96 = platform not found

### ISSUE THREAD

**Issue by adizag** [andersonshatch/midea-ac-py#2]
Hi

After upgrading to 0.96 got a validation error message:

Configuration invalid 
CHECK CONFIG
Platform not found: climate.midea

**Comment by Maczuga** [comment]
Are you sure you are using this fork, and not the original one "NeoAcheron/midea-ac-py"?

This fork is fully compatible with 0.96, but the structure is different, so you have to remove old component + dep and install this one.

**Comment by adizag** [comment]
I had to delete all files from both locations and copy again the main midea lib - and BAM!!!
great work out there guys.
Closing the issue.
