### ISSUE TITLE
Question - Porting to different home automation software

### ISSUE THREAD

**Issue by gelsas** [andersonshatch/midea-ac-py#21]
Hello,

Your repository is the most up to date implementation for Midea ac controlling.

That's why I would like to ask if you could give me any direction on how to port this to work with openhab. 
The most important thing would be the fan only fix how does it work? 

(There already is some basic implementation for openhab (https://github.com/JacekDob/midea-openhab/) but with that solution the same 17 degree fan only mode issue is present. 
Furthermore I am not sure how up to date that version is, where there any big addional features you made to the script/library?)

Best,
gelsas

**Comment by andersonshatch** [comment]
Hey gelsas!

The fan only workaround when enabled stops the polling for the current state of the AC unit, so the state is maintained only within the Home Assistant component. This means, if the state is altered with the AC remote or app, Home Assistant's state becomes incorrect, as the polling for current state is stopped.
This was necessary though, as the call to get current state has the annoying side effect of switching to fan only mode, for some models including mine.
This is the associated section in the component code where the fan only workaround lives: https://github.com/andersonshatch/midea-ac-py/blob/master/custom_components/midea/climate.py#L103:L111

As for the [underlying library](https://github.com/andersonshatch/midea-ac-lib), I think the only main change was something to handle the recovery of sessions. It should be in the last few commits, as I've not made much change there. Most of it remains a mystery to me.

Good luck!

**Comment by hillaliy** [comment]
can this work on homebridge?

**Comment by andersonshatch** [comment]
The library it uses would have to be rewritten in JavaScript, then I suppose it could. 
Seems a lot of work, especially given Home Assistant can already expose it to HomeKit just as Homebridge would.
