### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Cireasa23** [andersonshatch/midea-ac-py#25]
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 10:29:26 PM (5 occurrences)
Last logged: 10:29:29 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for midea doing I/O at custom_components/midea/climate.py, line 57: devices = client.devices()

**Comment by Dza-byte** [comment]
I am receiving the same error, since updating to 0.109.6 (was previously on 108)

**Comment by Cireasa23** [comment]
In 108 it was not present. :)

Catalin Cireasa
catalin.cireasa@gmail.com
