### ISSUE TITLE
Adjust/disregard internal thermostat?

### ISSUE THREAD

**Issue by jhavens12** [andersonshatch/midea-ac-py#28]
**Is your feature request related to a problem? Please describe.**
I am frustrated with how volatile the internal thermostat is

**Describe the solution you'd like**
I would like a way to disable or override the internal thermostat so the AC stops automatically shutting off when it thinks the target temperature is reached

**Describe alternatives you've considered**
Is it possible to physically disable the internal temperature sensor and instead use an external temp sensor through home assistant?

**Additional context**
The AC constantly turning off when the target temperature is "reached" is extremely frustrating, I'm trying to find a workaround. Thanks!

**Comment by aa755** [comment]
your IR remote control may have a "follow me" feature to set the AC to use the sensor in the remote.

**Comment by andersonshatch** [comment]
Library issue if anything, no idea how to implement.
