### ISSUE TITLE
Multi device suport

### ISSUE THREAD

**Issue by msanchezt** [andersonshatch/midea-ac-py#4]
I have 2 devices registered on my Net Home Plus App, but Home Assistant is only showing 1 of the 2 devices.

Is this some kind of limitation on the coding, or should it be showing the 2 devices (actually, as many as there are present on the NetHome Plus app).

**Comment by andersonshatch** [comment]
As far as I know, this should work, based off of the [loop here](https://github.com/andersonshatch/midea-ac-py/blob/aa423f610e384f75eeaa1a398997ced9bbf83c69/custom_components/midea/climate.py#L55)

Do you see log output detailing all the devices on your account?
Any unsupported device message like [from here](https://github.com/andersonshatch/midea-ac-py/blob/aa423f610e384f75eeaa1a398997ced9bbf83c69/custom_components/midea/climate.py#L61)?

**Comment by msanchezt** [comment]
I have 2 devices, same model. 1 is showing on HA while the other is not.
This is the only error I'm getting after restarting Home Assistant:

```

> Log Details (ERROR)
> Sat Aug 03 2019 12:01:05 GMT+0200 (Central European Summer Time)
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 365, in _async_add_entity
>     await entity.async_update_ha_state()
>   File "/usr/src/app/homeassistant/helpers/entity.py", line 226, in async_update_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/app/homeassistant/helpers/entity.py", line 249, in _async_write_ha_state
>     state = self.state
>   File "/usr/src/app/homeassistant/components/climate/__init__.py", line 155, in state
>     return self.hvac_mode
>   File "/config/custom_components/midea/climate.py", line 208, in hvac_mode
>     self._device.operational_mode = ac.operational_mode_enum[self._old_state.state]
>   File "/usr/local/lib/python3.7/enum.py", line 352, in __getitem__
>     return cls._member_map_[name]
> KeyError: 'unavailable'

```

**Comment by andersonshatch** [comment]
Thanks for the stack trace, that was probably the issue... I've fixed that now with 9974fb1c44c194b7364c1c213a0f6be51404d071 
Let me know if it works!

**Comment by msanchezt** [comment]
Thanks for the quick response. Now I get this other error:

> 
> Log Details (ERROR)
> Sun Aug 04 2019 14:55:31 GMT+0200 (Central European Summer Time)
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 365, in _async_add_entity
>     await entity.async_update_ha_state()
>   File "/usr/src/app/homeassistant/helpers/entity.py", line 226, in async_update_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/app/homeassistant/helpers/entity.py", line 256, in _async_write_ha_state
>     attr.update(self.state_attributes or {})
>   File "/config/custom_components/midea/climate.py", line 113, in state_attributes
>     attrs = super().state_attributes
>   File "/usr/src/app/homeassistant/components/climate/__init__.py", line 169, in state_attributes
>     ATTR_HVAC_MODES: self.hvac_modes,
>   File "/config/custom_components/midea/climate.py", line 137, in hvac_modes
>     return self._old_state.attributes['hvac_modes']
> KeyError: 'hvac_modes'

**Comment by andersonshatch** [comment]
whoops... yeah fixed those up now too.

**Comment by msanchezt** [comment]
Now it's working like a charm for both devices, you are a genius!

For the first error I guess "unavailable" state was not supported?

For the second one you fixed, not sure..

**Comment by andersonshatch** [comment]
2nd part was just to handle restoring from home assistant's old state properly, when maybe some data wasn't there in the old state.
