### ISSUE TITLE
2 @property should_poll in FAN WORKAROUND

### ISSUE THREAD

**Issue by adizag** [andersonshatch/midea-ac-py#6]
hi,

in the FAN WORKAROUND branch there are 2 instances of 
@property
    def should_poll(self)

line 163:
`    def should_poll(self):
        return not self._use_fan_only_workaround`

Line 172:
`    def should_poll(self):
        """Poll the appliance for changes, there is no notification capability in the Midea API"""
        return False`

No device update in this (last) version
thanks!

**Comment by andersonshatch** [comment]
Had this fixed locally but I guess I forgot to push. Pushed now.
Does polling work now?

**Comment by adizag** [comment]
Hi
Strangest  thing- when you mailed me regarding the double poll and the fixed code (Jul 30), i've tried it and IT WORKED! 
Unfortunately, same day my RPI just died a few hrs later.....
I recovered yesterday the hass, but now, using your freshly fixed code - the poll doesn't work. No device state update.

Additionally, 2 out of my 5 ac (previously appended) were no detected at all this time. 
These 2 were offline (at midea app) when I started hass, but even though they are now online, i get "entity not available" for them...

**Comment by andersonshatch** [comment]
could've been because this branch was rebased onto the master branch.
Added some changes now to erase restored state when polling, which seems to restore polling... and set my device to fan_only every time :)

**Comment by adizag** [comment]
MAN, that's working now! thank's!

it seems like your specific ACs has some problem with the FAN_ONLY. I wish I could assist you to solve it as you put your efforts to assist me...
meanwhile, I get some errors in my log, I'll put it in a new issue - hope it has something to do with your problem.

I'll keep updating, hoping it will only get better.

**Comment by andersonshatch** [comment]
🎉 Yay, glad we got there finally! I'll do some docs updates and merge to master soon
